# Copyright (C) 2022 Explore.dev Unipessoal Lda. All Rights Reserved.
# Use of this source code is governed by a license that can be
# found in the LICENSE file.

version: "3"

tasks:
  build:
    summary: |
      Builds Go files.

      Run with --watch or -w to watch for changes on Go files.
    cmds:
      - go build {{.CLI_ARGS}}
    sources:
      - ./*.go
