name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
    
      - name: Download dependencies
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest

      - name: Build
        run: task build
