name: Pull Request Build

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  pr-build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'run-build') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: task build
